name: FlixCore
version: '${project.version}'
main: com.abbas.FlixCore.FlixCore
api-version: '1.13'
authors:
  - Abbas
  - Cortz_Ex
  - 3bdoabk
  - Parsa
commands:
  gmc:
    description: Change game mode to creative
    usage: /<command>
  gms:
    description: Change game mode to survival
    usage: /<command>
  heal:
    description: Heal yourself or another player
  Backbed:
    description: Go back to your last location
    usage: /<command>
  help:
    description: Display help information
    usage: /<command>
  food:
    description: Make your Food Full
    usage: /<command>
  Farte:
    description: For FunCommand
    usage: /<command>
  Support:
    description: for SupportLink
    usage: /<command>
  Fly:
    description: Toggle Fly Mode
    usage: /<command>
  giveT:
    description: JustTestGiveBow
    usage: /<command>
  Vanish:
    description: For See Players Ban
    usage: /<command>
  pp:
    description: newDesign LockPlugins Server
    usage: /<command>
  about:
    description: For See About Server Like Version And ListPlugins
    usage: /<command>
  Tp:
    description: For Tp to any player
    usage: /<command>
  TpAll:
    description: For Tp all players to u
    usage: /<command>
  SetSpawn:
    description: SetSpawnCommand
    usage: /<command>
  Spawn:
    description: SpawnCommand
    usage: /<command>
    aliases:
      - lobby
      - hub
      - l
      - h
  Rank:
    description: For RankPlayer
    usage: /<command>
    aliases:
      - r
      - rp
      - ran
  broadcast:
    description: BroadcastMessage
    usage: /<command> <message>
    aliases:
      - bc
  ClearChat:
    description: ClearChat
    usage: /<command> [number of lines]
    aliases:
      - cc
  Ping:
    description: Show Your Ping
    usage: /<command>
  Rules:
    description: Show Server Rules
    usage: /<command>
    aliases:
      - rules
      - rls
      - rule
      - rl
permissions:
  Plugin.bypass:
    description: Allows access to Events
    default: op
  Plugin.Admin:
    description: Allows access to admin commands
    default: op
  Fly.Command:
    description: PlayerMainCommands
    default: op
  Fly.command.others:
    description: for Flay Others Players
    default: op
  spawn.Entity:
    description: for Spawn Entity Player Move
    default: op
  Player.TeleportBow:
    description: for give A bow if u dont have and command/giveT
    default: op
  FlixCore.setSpawn:
    description: For SetSpawn Players All
    default: op
  FlixCore.broadcast:
    description: For Broadcast Message
    default: op
  FlixCore.ClearChat:
    description: For ClearChat
    default: op
  FlixCore.Ping:
    description: For See Your Ping
    default: true
  Flixcore.JumpMode:
    description: For JumpMode
    default: op
  Flixcore.Rank:
    description: For See Your Rank
    default: true