name: MyPlugin
version: '${project.version}'
main: com.abbas.FlixCore.FlixCore
api-version: '1.13'
authors:
  - Abbas
  - Cortz_Ex
  - 3bdoabk
  - Parsa
commands:
  gmc:
    description: Change game mode to creative
    usage: /<command>
  gms:
    description: Change game mode to survival
    usage: /<command>
  heal:
    description: Heal yourself or another player
  Backbed:
    description: Go back to your last location
    usage: /<command>
  help:
    description: Display help information
    usage: /<command>
  food:
    description: Make your Food Full
    usage: /<command>
  Farte:
  Support:
    description: for SupportLink
    usage: /<command>
  Menu:
    usage: /<command>

  Fly:
    description: Toggle Fly Mode
    usage: /<command>


permissions:
  myplugin.bypass:
    description: Allows access to Events
    default: op
  Plugin.Admin:
    description: Allows access to admin commands
    default: op
  Fly.Command:
    description: PlayerMainCommands
    default: op
  Fly.command.others:
    description: for Flay Others Players
    default: op

